### ISSUE TITLE
Update documentation with an initial configuration for an ansible user

### ISSUE THREAD

**Issue by neikei** [IBM/ansible-power-vios#31]
**Is your feature request related to a problem? Please describe.**
As far as I understand for the collection the root user is needed on the VIO to execute the commands. I would prefer a dedicated user for ansible, but no matter how, there should be a documentation.

**Describe the solution you'd like**
Describe how a Ansible user can be set up.

1. AIX Toolbox should be available (README.md shows python2, but python3.9 is the current standard)
2. Create an ansible user: ```mkuser ansible```
3. Add your SSH public key: ```echo "your_ssh_pub_key" >> /home/ansible/.ssh/authorized_keys```
4. Add the following sudoers-rule for the Ansible user: ```ansible ALL=(ALL) NOPASSWD: ALL```
5. Run ansible with ```ansible_user=ansible```

**Describe alternatives you've considered**
Show your best practice. Maybe it is common to add the ssh key directly to the authorized_keys of root or to use padmin?

**Additional context**
It should be easy for new users.

**Comment by nitismis** [comment]
PR merged. Thanks @neikei
