### ISSUE TITLE
Restricted Shell

### ISSUE THREAD

**Issue by ulankford** [IBM/ansible-power-vios#8]
Just wondering, how does one get around the issue of the default restricted shell on offer from VIOS? Is the only way around this is to give the ansible user a non-restricted root shell, using the oem_setup_env command?

**Comment by neikei** [comment]
From my understanding the non-restricted shell is mandatory here. I opened an issue https://github.com/IBM/ansible-power-vios/issues/31 so that the topic hopefully will be documented soon.

**Comment by nitismis** [comment]
We have documented in the root directory README.md file.


    Modules included in this collection require administrator rights to run.
    It is recommended to create an ansible user with the proper level of privilege on the VIOS like this:
    command(1): oem_setup_env
    command(2): mkuser roles=PAdmin,CacheAdm,FSAdmin,pkgadm default_roles=PAdmin,CacheAdm,FSAdmin,pkgadm ansible
    To connect to the VIOS using this ansible user, specify user: ansible in the playbook or ansible_user=ansible in the inventory.
